-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2  Patch Version(s) 132427
-- Module  Version: 4.2
-- Mon Jul 20 17:23:59 2026

-- parameterized module component declaration
component fmac
    port (CLK0: in  std_logic; CE0: in  std_logic; RST0: in  std_logic; 
        ACCUMSLOAD: in  std_logic; ADDNSUB: in  std_logic; 
        A: in  std_logic_vector(31 downto 0); 
        B: in  std_logic_vector(31 downto 0); 
        LD: in  std_logic_vector(81 downto 0); OVERFLOW: out  std_logic; 
        ACCUM: out  std_logic_vector(81 downto 0));
end component;

-- parameterized module component instance
__ : fmac
    port map (CLK0=>__, CE0=>__, RST0=>__, ACCUMSLOAD=>__, ADDNSUB=>__, 
        A(31 downto 0)=>__, B(31 downto 0)=>__, LD(81 downto 0)=>__, 
        OVERFLOW=>__, ACCUM(81 downto 0)=>__);
