-- VHDL testbench template generated by SCUBA Diamond (64-bit) 3.14.0.75.2  Patch Version(s) 132427
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.std_logic_unsigned.all;

use IEEE.math_real.all;

use IEEE.numeric_std.all;

entity tb is
end entity tb;


architecture test of tb is 

    component fmac
        port (CLK0: in std_logic; CE0: in std_logic; RST0: in std_logic; 
        ACCUMSLOAD: in std_logic; ADDNSUB: in std_logic; 
        A : in std_logic_vector(31 downto 0); 
        B : in std_logic_vector(31 downto 0); 
        LD : in std_logic_vector(81 downto 0); OVERFLOW: out std_logic; 
        ACCUM : out std_logic_vector(81 downto 0)
    );
    end component;

    signal CLK0: std_logic := '0';
    signal CE0: std_logic := '0';
    signal RST0: std_logic := '0';
    signal ACCUMSLOAD: std_logic := '0';
    signal ADDNSUB: std_logic := '0';
    signal A : std_logic_vector(31 downto 0) := (others => '0');
    signal B : std_logic_vector(31 downto 0) := (others => '0');
    signal LD : std_logic_vector(81 downto 0) := (others => '0');
    signal OVERFLOW: std_logic;
    signal ACCUM : std_logic_vector(81 downto 0);
begin
    u1 : fmac
        port map (CLK0 => CLK0, CE0 => CE0, RST0 => RST0, ACCUMSLOAD => ACCUMSLOAD, 
            ADDNSUB => ADDNSUB, A => A, B => B, LD => LD, OVERFLOW => OVERFLOW, 
            ACCUM => ACCUM
        );

    CLK0 <= not CLK0 after 5.00 ns;

    process

    begin
      CE0 <= '1' ;
      wait;
    end process;

    process

    begin
      RST0 <= '1' ;
      wait for 100 ns;
      RST0 <= '0' ;
      wait;
    end process;

    process

    begin
      A <= (others => '0') ;
      for i in 0 to 200 loop
        wait for 10 ns;
        A <= A + '1' ;
      end loop;
      wait;
    end process;

    process

    begin
      B <= (others => '0') ;
      for i in 0 to 200 loop
        wait for 10 ns;
        B <= B + '1' ;
      end loop;
      wait;
    end process;

end architecture test;
