-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2  Patch Version(s) 132427
-- Module  Version: 5.7
-- Fri Jul 24 12:30:32 2026

-- parameterized module component declaration
component main_pll
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; CLKOS2: out  std_logic);
end component;

-- parameterized module component instance
__ : main_pll
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__, CLKOS2=>__);
