-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2  Patch Version(s) 132427
-- Module  Version: 3.5
--D:\lscc\diamond\3.14\ispfpga\bin\nt64\scuba.exe -w -n addsub -lang vhdl -synth synplify -bus_exp 7 -bb -arch sa5p00 -type addsub -width 64 -signed -output_reg -enable -pipeline 3 -fdc C:/dev/test_ecp5_and_diamond/ip/main_clocks/addsub/addsub.fdc 

-- Mon Jul 20 17:06:40 2026

library IEEE;
use IEEE.std_logic_1164.all;
library ECP5U;
use ECP5U.components.all;

entity addsub is
    port (
        DataA: in  std_logic_vector(63 downto 0); 
        DataB: in  std_logic_vector(63 downto 0); 
        Add_Sub: in  std_logic; 
        Clock: in  std_logic; 
        Reset: in  std_logic; 
        ClockEn: in  std_logic; 
        Result: out  std_logic_vector(63 downto 0));
end addsub;

architecture Structure of addsub is

    -- internal signal declarations
    signal r0_a63: std_logic;
    signal r0_a62: std_logic;
    signal r0_a61: std_logic;
    signal r0_a60: std_logic;
    signal r0_a59: std_logic;
    signal r0_a58: std_logic;
    signal r0_a57: std_logic;
    signal r0_a56: std_logic;
    signal r0_a55: std_logic;
    signal r0_a54: std_logic;
    signal r0_a53: std_logic;
    signal r0_a52: std_logic;
    signal r0_a51: std_logic;
    signal r0_a50: std_logic;
    signal r0_a49: std_logic;
    signal r0_a48: std_logic;
    signal r0_a47: std_logic;
    signal r0_a46: std_logic;
    signal r0_a45: std_logic;
    signal r0_a44: std_logic;
    signal r0_a43: std_logic;
    signal r0_a42: std_logic;
    signal r0_a41: std_logic;
    signal r0_a40: std_logic;
    signal r0_a39: std_logic;
    signal r0_a38: std_logic;
    signal r0_a37: std_logic;
    signal r0_a36: std_logic;
    signal r0_a35: std_logic;
    signal r0_a34: std_logic;
    signal r0_a33: std_logic;
    signal r0_a32: std_logic;
    signal r0_a31: std_logic;
    signal r0_b63: std_logic;
    signal r0_b62: std_logic;
    signal r0_b61: std_logic;
    signal r0_b60: std_logic;
    signal r0_b59: std_logic;
    signal r0_b58: std_logic;
    signal r0_b57: std_logic;
    signal r0_b56: std_logic;
    signal r0_b55: std_logic;
    signal r0_b54: std_logic;
    signal r0_b53: std_logic;
    signal r0_b52: std_logic;
    signal r0_b51: std_logic;
    signal r0_b50: std_logic;
    signal r0_b49: std_logic;
    signal r0_b48: std_logic;
    signal r0_b47: std_logic;
    signal r0_b46: std_logic;
    signal r0_b45: std_logic;
    signal r0_b44: std_logic;
    signal r0_b43: std_logic;
    signal r0_b42: std_logic;
    signal r0_b41: std_logic;
    signal r0_b40: std_logic;
    signal r0_b39: std_logic;
    signal r0_b38: std_logic;
    signal r0_b37: std_logic;
    signal r0_b36: std_logic;
    signal r0_b35: std_logic;
    signal r0_b34: std_logic;
    signal r0_b33: std_logic;
    signal r0_b32: std_logic;
    signal r0_b31: std_logic;
    signal r0_sum14: std_logic;
    signal r0_sum13: std_logic;
    signal r0_sum12: std_logic;
    signal r0_sum11: std_logic;
    signal r0_sum10: std_logic;
    signal r0_sum9: std_logic;
    signal r0_sum8: std_logic;
    signal r0_sum7: std_logic;
    signal r0_sum6: std_logic;
    signal r0_sum5: std_logic;
    signal r0_sum4: std_logic;
    signal r0_sum3: std_logic;
    signal r0_sum2: std_logic;
    signal r0_sum1: std_logic;
    signal r0_sum0: std_logic;
    signal addsub_ce0: std_logic;
    signal r1_a63: std_logic;
    signal r1_a62: std_logic;
    signal r1_a61: std_logic;
    signal r1_a60: std_logic;
    signal r1_a59: std_logic;
    signal r1_a58: std_logic;
    signal r1_a57: std_logic;
    signal r1_a56: std_logic;
    signal r1_a55: std_logic;
    signal r1_a54: std_logic;
    signal r1_a53: std_logic;
    signal r1_a52: std_logic;
    signal r1_a51: std_logic;
    signal r1_a50: std_logic;
    signal r1_a49: std_logic;
    signal r1_a48: std_logic;
    signal r1_a47: std_logic;
    signal r1_b63: std_logic;
    signal r1_b62: std_logic;
    signal r1_b61: std_logic;
    signal r1_b60: std_logic;
    signal r1_b59: std_logic;
    signal r1_b58: std_logic;
    signal r1_b57: std_logic;
    signal r1_b56: std_logic;
    signal r1_b55: std_logic;
    signal r1_b54: std_logic;
    signal r1_b53: std_logic;
    signal r1_b52: std_logic;
    signal r1_b51: std_logic;
    signal r1_b50: std_logic;
    signal r1_b49: std_logic;
    signal r1_b48: std_logic;
    signal r1_b47: std_logic;
    signal r1_sum30: std_logic;
    signal r1_sum29: std_logic;
    signal r1_sum28: std_logic;
    signal r1_sum27: std_logic;
    signal r1_sum26: std_logic;
    signal r1_sum25: std_logic;
    signal r1_sum24: std_logic;
    signal r1_sum23: std_logic;
    signal r1_sum22: std_logic;
    signal r1_sum21: std_logic;
    signal r1_sum20: std_logic;
    signal r1_sum19: std_logic;
    signal r1_sum18: std_logic;
    signal r1_sum17: std_logic;
    signal r1_sum16: std_logic;
    signal r1_sum15: std_logic;
    signal r1_sum14: std_logic;
    signal r1_sum13: std_logic;
    signal r1_sum12: std_logic;
    signal r1_sum11: std_logic;
    signal r1_sum10: std_logic;
    signal r1_sum9: std_logic;
    signal r1_sum8: std_logic;
    signal r1_sum7: std_logic;
    signal r1_sum6: std_logic;
    signal r1_sum5: std_logic;
    signal r1_sum4: std_logic;
    signal r1_sum3: std_logic;
    signal r1_sum2: std_logic;
    signal r1_sum1: std_logic;
    signal r1_sum0: std_logic;
    signal addsub_ce1: std_logic;
    signal r3_sum63: std_logic;
    signal r3_sum62: std_logic;
    signal r3_sum61: std_logic;
    signal r3_sum60: std_logic;
    signal r3_sum59: std_logic;
    signal r3_sum58: std_logic;
    signal r3_sum57: std_logic;
    signal r3_sum56: std_logic;
    signal r3_sum55: std_logic;
    signal r3_sum54: std_logic;
    signal r3_sum53: std_logic;
    signal r3_sum52: std_logic;
    signal r3_sum51: std_logic;
    signal r3_sum50: std_logic;
    signal r3_sum49: std_logic;
    signal r3_sum48: std_logic;
    signal r3_sum47: std_logic;
    signal r3_sum46: std_logic;
    signal r2_sum46: std_logic;
    signal r3_sum45: std_logic;
    signal r2_sum45: std_logic;
    signal r3_sum44: std_logic;
    signal r2_sum44: std_logic;
    signal r3_sum43: std_logic;
    signal r2_sum43: std_logic;
    signal r3_sum42: std_logic;
    signal r2_sum42: std_logic;
    signal r3_sum41: std_logic;
    signal r2_sum41: std_logic;
    signal r3_sum40: std_logic;
    signal r2_sum40: std_logic;
    signal r3_sum39: std_logic;
    signal r2_sum39: std_logic;
    signal r3_sum38: std_logic;
    signal r2_sum38: std_logic;
    signal r3_sum37: std_logic;
    signal r2_sum37: std_logic;
    signal r3_sum36: std_logic;
    signal r2_sum36: std_logic;
    signal r3_sum35: std_logic;
    signal r2_sum35: std_logic;
    signal r3_sum34: std_logic;
    signal r2_sum34: std_logic;
    signal r3_sum33: std_logic;
    signal r2_sum33: std_logic;
    signal r3_sum32: std_logic;
    signal r2_sum32: std_logic;
    signal r3_sum31: std_logic;
    signal r2_sum31: std_logic;
    signal r3_sum30: std_logic;
    signal r2_sum30: std_logic;
    signal r3_sum29: std_logic;
    signal r2_sum29: std_logic;
    signal r3_sum28: std_logic;
    signal r2_sum28: std_logic;
    signal r3_sum27: std_logic;
    signal r2_sum27: std_logic;
    signal r3_sum26: std_logic;
    signal r2_sum26: std_logic;
    signal r3_sum25: std_logic;
    signal r2_sum25: std_logic;
    signal r3_sum24: std_logic;
    signal r2_sum24: std_logic;
    signal r3_sum23: std_logic;
    signal r2_sum23: std_logic;
    signal r3_sum22: std_logic;
    signal r2_sum22: std_logic;
    signal r3_sum21: std_logic;
    signal r2_sum21: std_logic;
    signal r3_sum20: std_logic;
    signal r2_sum20: std_logic;
    signal r3_sum19: std_logic;
    signal r2_sum19: std_logic;
    signal r3_sum18: std_logic;
    signal r2_sum18: std_logic;
    signal r3_sum17: std_logic;
    signal r2_sum17: std_logic;
    signal r3_sum16: std_logic;
    signal r2_sum16: std_logic;
    signal r3_sum15: std_logic;
    signal r2_sum15: std_logic;
    signal r3_sum14: std_logic;
    signal r2_sum14: std_logic;
    signal r3_sum13: std_logic;
    signal r2_sum13: std_logic;
    signal r3_sum12: std_logic;
    signal r2_sum12: std_logic;
    signal r3_sum11: std_logic;
    signal r2_sum11: std_logic;
    signal r3_sum10: std_logic;
    signal r2_sum10: std_logic;
    signal r3_sum9: std_logic;
    signal r2_sum9: std_logic;
    signal r3_sum8: std_logic;
    signal r2_sum8: std_logic;
    signal r3_sum7: std_logic;
    signal r2_sum7: std_logic;
    signal r3_sum6: std_logic;
    signal r2_sum6: std_logic;
    signal r3_sum5: std_logic;
    signal r2_sum5: std_logic;
    signal r3_sum4: std_logic;
    signal r2_sum4: std_logic;
    signal r3_sum3: std_logic;
    signal r2_sum3: std_logic;
    signal r3_sum2: std_logic;
    signal r2_sum2: std_logic;
    signal r3_sum1: std_logic;
    signal r2_sum1: std_logic;
    signal r3_sum0: std_logic;
    signal addsub_ce2: std_logic;
    signal r2_sum0: std_logic;
    signal tsum0: std_logic;
    signal add_sub_inv: std_logic;
    signal precin: std_logic;
    signal tsum1: std_logic;
    signal tsum2: std_logic;
    signal co0: std_logic;
    signal tsum3: std_logic;
    signal tsum4: std_logic;
    signal co1: std_logic;
    signal tsum5: std_logic;
    signal tsum6: std_logic;
    signal co2: std_logic;
    signal tsum7: std_logic;
    signal tsum8: std_logic;
    signal co3: std_logic;
    signal tsum9: std_logic;
    signal tsum10: std_logic;
    signal co4: std_logic;
    signal tsum11: std_logic;
    signal tsum12: std_logic;
    signal co5: std_logic;
    signal tsum13: std_logic;
    signal tsum14: std_logic;
    signal co6: std_logic;
    signal co7d: std_logic;
    signal co7: std_logic;
    signal tsum15: std_logic;
    signal r0_b15: std_logic;
    signal addsub_8b0: std_logic;
    signal r0_a15: std_logic;
    signal addsub_cod_0: std_logic;
    signal groupcin: std_logic;
    signal tsum16: std_logic;
    signal tsum17: std_logic;
    signal r0_b17: std_logic;
    signal r0_b16: std_logic;
    signal r0_a17: std_logic;
    signal r0_a16: std_logic;
    signal co8: std_logic;
    signal tsum18: std_logic;
    signal tsum19: std_logic;
    signal r0_b19: std_logic;
    signal r0_b18: std_logic;
    signal r0_a19: std_logic;
    signal r0_a18: std_logic;
    signal co9: std_logic;
    signal tsum20: std_logic;
    signal tsum21: std_logic;
    signal r0_b21: std_logic;
    signal r0_b20: std_logic;
    signal r0_a21: std_logic;
    signal r0_a20: std_logic;
    signal co10: std_logic;
    signal tsum22: std_logic;
    signal tsum23: std_logic;
    signal r0_b23: std_logic;
    signal r0_b22: std_logic;
    signal r0_a23: std_logic;
    signal r0_a22: std_logic;
    signal co11: std_logic;
    signal tsum24: std_logic;
    signal tsum25: std_logic;
    signal r0_b25: std_logic;
    signal r0_b24: std_logic;
    signal r0_a25: std_logic;
    signal r0_a24: std_logic;
    signal co12: std_logic;
    signal tsum26: std_logic;
    signal tsum27: std_logic;
    signal r0_b27: std_logic;
    signal r0_b26: std_logic;
    signal r0_a27: std_logic;
    signal r0_a26: std_logic;
    signal co13: std_logic;
    signal tsum28: std_logic;
    signal tsum29: std_logic;
    signal r0_b29: std_logic;
    signal r0_b28: std_logic;
    signal r0_a29: std_logic;
    signal r0_a28: std_logic;
    signal co14: std_logic;
    signal tsum30: std_logic;
    signal co16: std_logic;
    signal addsub_as0: std_logic;
    signal r0_b30: std_logic;
    signal addsub_as0_inv: std_logic;
    signal r0_a30: std_logic;
    signal co15: std_logic;
    signal tsum31: std_logic;
    signal r1_b31: std_logic;
    signal addsub_16b0: std_logic;
    signal r1_a31: std_logic;
    signal addsub_cod_1: std_logic;
    signal groupcin_1: std_logic;
    signal tsum32: std_logic;
    signal tsum33: std_logic;
    signal r1_b33: std_logic;
    signal r1_b32: std_logic;
    signal r1_a33: std_logic;
    signal r1_a32: std_logic;
    signal co16_1: std_logic;
    signal tsum34: std_logic;
    signal tsum35: std_logic;
    signal r1_b35: std_logic;
    signal r1_b34: std_logic;
    signal r1_a35: std_logic;
    signal r1_a34: std_logic;
    signal co17: std_logic;
    signal tsum36: std_logic;
    signal tsum37: std_logic;
    signal r1_b37: std_logic;
    signal r1_b36: std_logic;
    signal r1_a37: std_logic;
    signal r1_a36: std_logic;
    signal co18: std_logic;
    signal tsum38: std_logic;
    signal tsum39: std_logic;
    signal r1_b39: std_logic;
    signal r1_b38: std_logic;
    signal r1_a39: std_logic;
    signal r1_a38: std_logic;
    signal co19: std_logic;
    signal tsum40: std_logic;
    signal tsum41: std_logic;
    signal r1_b41: std_logic;
    signal r1_b40: std_logic;
    signal r1_a41: std_logic;
    signal r1_a40: std_logic;
    signal co20: std_logic;
    signal tsum42: std_logic;
    signal tsum43: std_logic;
    signal r1_b43: std_logic;
    signal r1_b42: std_logic;
    signal r1_a43: std_logic;
    signal r1_a42: std_logic;
    signal co21: std_logic;
    signal tsum44: std_logic;
    signal tsum45: std_logic;
    signal r1_b45: std_logic;
    signal r1_b44: std_logic;
    signal r1_a45: std_logic;
    signal r1_a44: std_logic;
    signal co22: std_logic;
    signal tsum46: std_logic;
    signal co24: std_logic;
    signal addsub_as1: std_logic;
    signal scuba_vlo: std_logic;
    signal r1_b46: std_logic;
    signal addsub_as1_inv: std_logic;
    signal r1_a46: std_logic;
    signal co23: std_logic;
    signal tsum47: std_logic;
    signal r2_b47: std_logic;
    signal addsub_24b0: std_logic;
    signal r2_a47: std_logic;
    signal addsub_cod_2: std_logic;
    signal groupcin_2: std_logic;
    signal tsum48: std_logic;
    signal tsum49: std_logic;
    signal r2_b49: std_logic;
    signal r2_b48: std_logic;
    signal r2_a49: std_logic;
    signal r2_a48: std_logic;
    signal co24_1: std_logic;
    signal tsum50: std_logic;
    signal tsum51: std_logic;
    signal r2_b51: std_logic;
    signal r2_b50: std_logic;
    signal r2_a51: std_logic;
    signal r2_a50: std_logic;
    signal co25: std_logic;
    signal tsum52: std_logic;
    signal tsum53: std_logic;
    signal r2_b53: std_logic;
    signal r2_b52: std_logic;
    signal r2_a53: std_logic;
    signal r2_a52: std_logic;
    signal co26: std_logic;
    signal tsum54: std_logic;
    signal tsum55: std_logic;
    signal r2_b55: std_logic;
    signal r2_b54: std_logic;
    signal r2_a55: std_logic;
    signal r2_a54: std_logic;
    signal co27: std_logic;
    signal tsum56: std_logic;
    signal tsum57: std_logic;
    signal r2_b57: std_logic;
    signal r2_b56: std_logic;
    signal r2_a57: std_logic;
    signal r2_a56: std_logic;
    signal co28: std_logic;
    signal tsum58: std_logic;
    signal tsum59: std_logic;
    signal r2_b59: std_logic;
    signal r2_b58: std_logic;
    signal r2_a59: std_logic;
    signal r2_a58: std_logic;
    signal co29: std_logic;
    signal tsum60: std_logic;
    signal tsum61: std_logic;
    signal r2_b61: std_logic;
    signal r2_b60: std_logic;
    signal r2_a61: std_logic;
    signal r2_a60: std_logic;
    signal co30: std_logic;
    signal tsum62: std_logic;
    signal tsum63: std_logic;
    signal addsub_as2: std_logic;
    signal scuba_vhi: std_logic;
    signal r2_b63: std_logic;
    signal r2_b62: std_logic;
    signal r2_a63: std_logic;
    signal r2_a62: std_logic;
    signal co31: std_logic;

    attribute GSR : string; 
    attribute GSR of FF_363 : label is "ENABLED";
    attribute GSR of FF_362 : label is "ENABLED";
    attribute GSR of FF_361 : label is "ENABLED";
    attribute GSR of FF_360 : label is "ENABLED";
    attribute GSR of FF_359 : label is "ENABLED";
    attribute GSR of FF_358 : label is "ENABLED";
    attribute GSR of FF_357 : label is "ENABLED";
    attribute GSR of FF_356 : label is "ENABLED";
    attribute GSR of FF_355 : label is "ENABLED";
    attribute GSR of FF_354 : label is "ENABLED";
    attribute GSR of FF_353 : label is "ENABLED";
    attribute GSR of FF_352 : label is "ENABLED";
    attribute GSR of FF_351 : label is "ENABLED";
    attribute GSR of FF_350 : label is "ENABLED";
    attribute GSR of FF_349 : label is "ENABLED";
    attribute GSR of FF_348 : label is "ENABLED";
    attribute GSR of FF_347 : label is "ENABLED";
    attribute GSR of FF_346 : label is "ENABLED";
    attribute GSR of FF_345 : label is "ENABLED";
    attribute GSR of FF_344 : label is "ENABLED";
    attribute GSR of FF_343 : label is "ENABLED";
    attribute GSR of FF_342 : label is "ENABLED";
    attribute GSR of FF_341 : label is "ENABLED";
    attribute GSR of FF_340 : label is "ENABLED";
    attribute GSR of FF_339 : label is "ENABLED";
    attribute GSR of FF_338 : label is "ENABLED";
    attribute GSR of FF_337 : label is "ENABLED";
    attribute GSR of FF_336 : label is "ENABLED";
    attribute GSR of FF_335 : label is "ENABLED";
    attribute GSR of FF_334 : label is "ENABLED";
    attribute GSR of FF_333 : label is "ENABLED";
    attribute GSR of FF_332 : label is "ENABLED";
    attribute GSR of FF_331 : label is "ENABLED";
    attribute GSR of FF_330 : label is "ENABLED";
    attribute GSR of FF_329 : label is "ENABLED";
    attribute GSR of FF_328 : label is "ENABLED";
    attribute GSR of FF_327 : label is "ENABLED";
    attribute GSR of FF_326 : label is "ENABLED";
    attribute GSR of FF_325 : label is "ENABLED";
    attribute GSR of FF_324 : label is "ENABLED";
    attribute GSR of FF_323 : label is "ENABLED";
    attribute GSR of FF_322 : label is "ENABLED";
    attribute GSR of FF_321 : label is "ENABLED";
    attribute GSR of FF_320 : label is "ENABLED";
    attribute GSR of FF_319 : label is "ENABLED";
    attribute GSR of FF_318 : label is "ENABLED";
    attribute GSR of FF_317 : label is "ENABLED";
    attribute GSR of FF_316 : label is "ENABLED";
    attribute GSR of FF_315 : label is "ENABLED";
    attribute GSR of FF_314 : label is "ENABLED";
    attribute GSR of FF_313 : label is "ENABLED";
    attribute GSR of FF_312 : label is "ENABLED";
    attribute GSR of FF_311 : label is "ENABLED";
    attribute GSR of FF_310 : label is "ENABLED";
    attribute GSR of FF_309 : label is "ENABLED";
    attribute GSR of FF_308 : label is "ENABLED";
    attribute GSR of FF_307 : label is "ENABLED";
    attribute GSR of FF_306 : label is "ENABLED";
    attribute GSR of FF_305 : label is "ENABLED";
    attribute GSR of FF_304 : label is "ENABLED";
    attribute GSR of FF_303 : label is "ENABLED";
    attribute GSR of FF_302 : label is "ENABLED";
    attribute GSR of FF_301 : label is "ENABLED";
    attribute GSR of FF_300 : label is "ENABLED";
    attribute GSR of FF_299 : label is "ENABLED";
    attribute GSR of FF_298 : label is "ENABLED";
    attribute GSR of FF_297 : label is "ENABLED";
    attribute GSR of FF_296 : label is "ENABLED";
    attribute GSR of FF_295 : label is "ENABLED";
    attribute GSR of FF_294 : label is "ENABLED";
    attribute GSR of FF_293 : label is "ENABLED";
    attribute GSR of FF_292 : label is "ENABLED";
    attribute GSR of FF_291 : label is "ENABLED";
    attribute GSR of FF_290 : label is "ENABLED";
    attribute GSR of FF_289 : label is "ENABLED";
    attribute GSR of FF_288 : label is "ENABLED";
    attribute GSR of FF_287 : label is "ENABLED";
    attribute GSR of FF_286 : label is "ENABLED";
    attribute GSR of FF_285 : label is "ENABLED";
    attribute GSR of FF_284 : label is "ENABLED";
    attribute GSR of FF_283 : label is "ENABLED";
    attribute GSR of FF_282 : label is "ENABLED";
    attribute GSR of FF_281 : label is "ENABLED";
    attribute GSR of FF_280 : label is "ENABLED";
    attribute GSR of FF_279 : label is "ENABLED";
    attribute GSR of FF_278 : label is "ENABLED";
    attribute GSR of FF_277 : label is "ENABLED";
    attribute GSR of FF_276 : label is "ENABLED";
    attribute GSR of FF_275 : label is "ENABLED";
    attribute GSR of FF_274 : label is "ENABLED";
    attribute GSR of FF_273 : label is "ENABLED";
    attribute GSR of FF_272 : label is "ENABLED";
    attribute GSR of FF_271 : label is "ENABLED";
    attribute GSR of FF_270 : label is "ENABLED";
    attribute GSR of FF_269 : label is "ENABLED";
    attribute GSR of FF_268 : label is "ENABLED";
    attribute GSR of FF_267 : label is "ENABLED";
    attribute GSR of FF_266 : label is "ENABLED";
    attribute GSR of FF_265 : label is "ENABLED";
    attribute GSR of FF_264 : label is "ENABLED";
    attribute GSR of FF_263 : label is "ENABLED";
    attribute GSR of FF_262 : label is "ENABLED";
    attribute GSR of FF_261 : label is "ENABLED";
    attribute GSR of FF_260 : label is "ENABLED";
    attribute GSR of FF_259 : label is "ENABLED";
    attribute GSR of FF_258 : label is "ENABLED";
    attribute GSR of FF_257 : label is "ENABLED";
    attribute GSR of FF_256 : label is "ENABLED";
    attribute GSR of FF_255 : label is "ENABLED";
    attribute GSR of FF_254 : label is "ENABLED";
    attribute GSR of FF_253 : label is "ENABLED";
    attribute GSR of FF_252 : label is "ENABLED";
    attribute GSR of FF_251 : label is "ENABLED";
    attribute GSR of FF_250 : label is "ENABLED";
    attribute GSR of FF_249 : label is "ENABLED";
    attribute GSR of FF_248 : label is "ENABLED";
    attribute GSR of FF_247 : label is "ENABLED";
    attribute GSR of FF_246 : label is "ENABLED";
    attribute GSR of FF_245 : label is "ENABLED";
    attribute GSR of FF_244 : label is "ENABLED";
    attribute GSR of FF_243 : label is "ENABLED";
    attribute GSR of FF_242 : label is "ENABLED";
    attribute GSR of FF_241 : label is "ENABLED";
    attribute GSR of FF_240 : label is "ENABLED";
    attribute GSR of FF_239 : label is "ENABLED";
    attribute GSR of FF_238 : label is "ENABLED";
    attribute GSR of FF_237 : label is "ENABLED";
    attribute GSR of FF_236 : label is "ENABLED";
    attribute GSR of FF_235 : label is "ENABLED";
    attribute GSR of FF_234 : label is "ENABLED";
    attribute GSR of FF_233 : label is "ENABLED";
    attribute GSR of FF_232 : label is "ENABLED";
    attribute GSR of FF_231 : label is "ENABLED";
    attribute GSR of FF_230 : label is "ENABLED";
    attribute GSR of FF_229 : label is "ENABLED";
    attribute GSR of FF_228 : label is "ENABLED";
    attribute GSR of FF_227 : label is "ENABLED";
    attribute GSR of FF_226 : label is "ENABLED";
    attribute GSR of FF_225 : label is "ENABLED";
    attribute GSR of FF_224 : label is "ENABLED";
    attribute GSR of FF_223 : label is "ENABLED";
    attribute GSR of FF_222 : label is "ENABLED";
    attribute GSR of FF_221 : label is "ENABLED";
    attribute GSR of FF_220 : label is "ENABLED";
    attribute GSR of FF_219 : label is "ENABLED";
    attribute GSR of FF_218 : label is "ENABLED";
    attribute GSR of FF_217 : label is "ENABLED";
    attribute GSR of FF_216 : label is "ENABLED";
    attribute GSR of FF_215 : label is "ENABLED";
    attribute GSR of FF_214 : label is "ENABLED";
    attribute GSR of FF_213 : label is "ENABLED";
    attribute GSR of FF_212 : label is "ENABLED";
    attribute GSR of FF_211 : label is "ENABLED";
    attribute GSR of FF_210 : label is "ENABLED";
    attribute GSR of FF_209 : label is "ENABLED";
    attribute GSR of FF_208 : label is "ENABLED";
    attribute GSR of FF_207 : label is "ENABLED";
    attribute GSR of FF_206 : label is "ENABLED";
    attribute GSR of FF_205 : label is "ENABLED";
    attribute GSR of FF_204 : label is "ENABLED";
    attribute GSR of FF_203 : label is "ENABLED";
    attribute GSR of FF_202 : label is "ENABLED";
    attribute GSR of FF_201 : label is "ENABLED";
    attribute GSR of FF_200 : label is "ENABLED";
    attribute GSR of FF_199 : label is "ENABLED";
    attribute GSR of FF_198 : label is "ENABLED";
    attribute GSR of FF_197 : label is "ENABLED";
    attribute GSR of FF_196 : label is "ENABLED";
    attribute GSR of FF_195 : label is "ENABLED";
    attribute GSR of FF_194 : label is "ENABLED";
    attribute GSR of FF_193 : label is "ENABLED";
    attribute GSR of FF_192 : label is "ENABLED";
    attribute GSR of FF_191 : label is "ENABLED";
    attribute GSR of FF_190 : label is "ENABLED";
    attribute GSR of FF_189 : label is "ENABLED";
    attribute GSR of FF_188 : label is "ENABLED";
    attribute GSR of FF_187 : label is "ENABLED";
    attribute GSR of FF_186 : label is "ENABLED";
    attribute GSR of FF_185 : label is "ENABLED";
    attribute GSR of FF_184 : label is "ENABLED";
    attribute GSR of FF_183 : label is "ENABLED";
    attribute GSR of FF_182 : label is "ENABLED";
    attribute GSR of FF_181 : label is "ENABLED";
    attribute GSR of FF_180 : label is "ENABLED";
    attribute GSR of FF_179 : label is "ENABLED";
    attribute GSR of FF_178 : label is "ENABLED";
    attribute GSR of FF_177 : label is "ENABLED";
    attribute GSR of FF_176 : label is "ENABLED";
    attribute GSR of FF_175 : label is "ENABLED";
    attribute GSR of FF_174 : label is "ENABLED";
    attribute GSR of FF_173 : label is "ENABLED";
    attribute GSR of FF_172 : label is "ENABLED";
    attribute GSR of FF_171 : label is "ENABLED";
    attribute GSR of FF_170 : label is "ENABLED";
    attribute GSR of FF_169 : label is "ENABLED";
    attribute GSR of FF_168 : label is "ENABLED";
    attribute GSR of FF_167 : label is "ENABLED";
    attribute GSR of FF_166 : label is "ENABLED";
    attribute GSR of FF_165 : label is "ENABLED";
    attribute GSR of FF_164 : label is "ENABLED";
    attribute GSR of FF_163 : label is "ENABLED";
    attribute GSR of FF_162 : label is "ENABLED";
    attribute GSR of FF_161 : label is "ENABLED";
    attribute GSR of FF_160 : label is "ENABLED";
    attribute GSR of FF_159 : label is "ENABLED";
    attribute GSR of FF_158 : label is "ENABLED";
    attribute GSR of FF_157 : label is "ENABLED";
    attribute GSR of FF_156 : label is "ENABLED";
    attribute GSR of FF_155 : label is "ENABLED";
    attribute GSR of FF_154 : label is "ENABLED";
    attribute GSR of FF_153 : label is "ENABLED";
    attribute GSR of FF_152 : label is "ENABLED";
    attribute GSR of FF_151 : label is "ENABLED";
    attribute GSR of FF_150 : label is "ENABLED";
    attribute GSR of FF_149 : label is "ENABLED";
    attribute GSR of FF_148 : label is "ENABLED";
    attribute GSR of FF_147 : label is "ENABLED";
    attribute GSR of FF_146 : label is "ENABLED";
    attribute GSR of FF_145 : label is "ENABLED";
    attribute GSR of FF_144 : label is "ENABLED";
    attribute GSR of FF_143 : label is "ENABLED";
    attribute GSR of FF_142 : label is "ENABLED";
    attribute GSR of FF_141 : label is "ENABLED";
    attribute GSR of FF_140 : label is "ENABLED";
    attribute GSR of FF_139 : label is "ENABLED";
    attribute GSR of FF_138 : label is "ENABLED";
    attribute GSR of FF_137 : label is "ENABLED";
    attribute GSR of FF_136 : label is "ENABLED";
    attribute GSR of FF_135 : label is "ENABLED";
    attribute GSR of FF_134 : label is "ENABLED";
    attribute GSR of FF_133 : label is "ENABLED";
    attribute GSR of FF_132 : label is "ENABLED";
    attribute GSR of FF_131 : label is "ENABLED";
    attribute GSR of FF_130 : label is "ENABLED";
    attribute GSR of FF_129 : label is "ENABLED";
    attribute GSR of FF_128 : label is "ENABLED";
    attribute GSR of FF_127 : label is "ENABLED";
    attribute GSR of FF_126 : label is "ENABLED";
    attribute GSR of FF_125 : label is "ENABLED";
    attribute GSR of FF_124 : label is "ENABLED";
    attribute GSR of FF_123 : label is "ENABLED";
    attribute GSR of FF_122 : label is "ENABLED";
    attribute GSR of FF_121 : label is "ENABLED";
    attribute GSR of FF_120 : label is "ENABLED";
    attribute GSR of FF_119 : label is "ENABLED";
    attribute GSR of FF_118 : label is "ENABLED";
    attribute GSR of FF_117 : label is "ENABLED";
    attribute GSR of FF_116 : label is "ENABLED";
    attribute GSR of FF_115 : label is "ENABLED";
    attribute GSR of FF_114 : label is "ENABLED";
    attribute GSR of FF_113 : label is "ENABLED";
    attribute GSR of FF_112 : label is "ENABLED";
    attribute GSR of FF_111 : label is "ENABLED";
    attribute GSR of FF_110 : label is "ENABLED";
    attribute GSR of FF_109 : label is "ENABLED";
    attribute GSR of FF_108 : label is "ENABLED";
    attribute GSR of FF_107 : label is "ENABLED";
    attribute GSR of FF_106 : label is "ENABLED";
    attribute GSR of FF_105 : label is "ENABLED";
    attribute GSR of FF_104 : label is "ENABLED";
    attribute GSR of FF_103 : label is "ENABLED";
    attribute GSR of FF_102 : label is "ENABLED";
    attribute GSR of FF_101 : label is "ENABLED";
    attribute GSR of FF_100 : label is "ENABLED";
    attribute GSR of FF_99 : label is "ENABLED";
    attribute GSR of FF_98 : label is "ENABLED";
    attribute GSR of FF_97 : label is "ENABLED";
    attribute GSR of FF_96 : label is "ENABLED";
    attribute GSR of FF_95 : label is "ENABLED";
    attribute GSR of FF_94 : label is "ENABLED";
    attribute GSR of FF_93 : label is "ENABLED";
    attribute GSR of FF_92 : label is "ENABLED";
    attribute GSR of FF_91 : label is "ENABLED";
    attribute GSR of FF_90 : label is "ENABLED";
    attribute GSR of FF_89 : label is "ENABLED";
    attribute GSR of FF_88 : label is "ENABLED";
    attribute GSR of FF_87 : label is "ENABLED";
    attribute GSR of FF_86 : label is "ENABLED";
    attribute GSR of FF_85 : label is "ENABLED";
    attribute GSR of FF_84 : label is "ENABLED";
    attribute GSR of FF_83 : label is "ENABLED";
    attribute GSR of FF_82 : label is "ENABLED";
    attribute GSR of FF_81 : label is "ENABLED";
    attribute GSR of FF_80 : label is "ENABLED";
    attribute GSR of FF_79 : label is "ENABLED";
    attribute GSR of FF_78 : label is "ENABLED";
    attribute GSR of FF_77 : label is "ENABLED";
    attribute GSR of FF_76 : label is "ENABLED";
    attribute GSR of FF_75 : label is "ENABLED";
    attribute GSR of FF_74 : label is "ENABLED";
    attribute GSR of FF_73 : label is "ENABLED";
    attribute GSR of FF_72 : label is "ENABLED";
    attribute GSR of FF_71 : label is "ENABLED";
    attribute GSR of FF_70 : label is "ENABLED";
    attribute GSR of FF_69 : label is "ENABLED";
    attribute GSR of FF_68 : label is "ENABLED";
    attribute GSR of FF_67 : label is "ENABLED";
    attribute GSR of FF_66 : label is "ENABLED";
    attribute GSR of FF_65 : label is "ENABLED";
    attribute GSR of FF_64 : label is "ENABLED";
    attribute GSR of FF_63 : label is "ENABLED";
    attribute GSR of FF_62 : label is "ENABLED";
    attribute GSR of FF_61 : label is "ENABLED";
    attribute GSR of FF_60 : label is "ENABLED";
    attribute GSR of FF_59 : label is "ENABLED";
    attribute GSR of FF_58 : label is "ENABLED";
    attribute GSR of FF_57 : label is "ENABLED";
    attribute GSR of FF_56 : label is "ENABLED";
    attribute GSR of FF_55 : label is "ENABLED";
    attribute GSR of FF_54 : label is "ENABLED";
    attribute GSR of FF_53 : label is "ENABLED";
    attribute GSR of FF_52 : label is "ENABLED";
    attribute GSR of FF_51 : label is "ENABLED";
    attribute GSR of FF_50 : label is "ENABLED";
    attribute GSR of FF_49 : label is "ENABLED";
    attribute GSR of FF_48 : label is "ENABLED";
    attribute GSR of FF_47 : label is "ENABLED";
    attribute GSR of FF_46 : label is "ENABLED";
    attribute GSR of FF_45 : label is "ENABLED";
    attribute GSR of FF_44 : label is "ENABLED";
    attribute GSR of FF_43 : label is "ENABLED";
    attribute GSR of FF_42 : label is "ENABLED";
    attribute GSR of FF_41 : label is "ENABLED";
    attribute GSR of FF_40 : label is "ENABLED";
    attribute GSR of FF_39 : label is "ENABLED";
    attribute GSR of FF_38 : label is "ENABLED";
    attribute GSR of FF_37 : label is "ENABLED";
    attribute GSR of FF_36 : label is "ENABLED";
    attribute GSR of FF_35 : label is "ENABLED";
    attribute GSR of FF_34 : label is "ENABLED";
    attribute GSR of FF_33 : label is "ENABLED";
    attribute GSR of FF_32 : label is "ENABLED";
    attribute GSR of FF_31 : label is "ENABLED";
    attribute GSR of FF_30 : label is "ENABLED";
    attribute GSR of FF_29 : label is "ENABLED";
    attribute GSR of FF_28 : label is "ENABLED";
    attribute GSR of FF_27 : label is "ENABLED";
    attribute GSR of FF_26 : label is "ENABLED";
    attribute GSR of FF_25 : label is "ENABLED";
    attribute GSR of FF_24 : label is "ENABLED";
    attribute GSR of FF_23 : label is "ENABLED";
    attribute GSR of FF_22 : label is "ENABLED";
    attribute GSR of FF_21 : label is "ENABLED";
    attribute GSR of FF_20 : label is "ENABLED";
    attribute GSR of FF_19 : label is "ENABLED";
    attribute GSR of FF_18 : label is "ENABLED";
    attribute GSR of FF_17 : label is "ENABLED";
    attribute GSR of FF_16 : label is "ENABLED";
    attribute GSR of FF_15 : label is "ENABLED";
    attribute GSR of FF_14 : label is "ENABLED";
    attribute GSR of FF_13 : label is "ENABLED";
    attribute GSR of FF_12 : label is "ENABLED";
    attribute GSR of FF_11 : label is "ENABLED";
    attribute GSR of FF_10 : label is "ENABLED";
    attribute GSR of FF_9 : label is "ENABLED";
    attribute GSR of FF_8 : label is "ENABLED";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    INV_2: INV
        port map (A=>Add_Sub, Z=>add_sub_inv);

    XNOR2_t2: XNOR2
        port map (A=>addsub_cod_0, B=>addsub_as0, Z=>addsub_8b0);

    INV_1: INV
        port map (A=>addsub_as0, Z=>addsub_as0_inv);

    XNOR2_t1: XNOR2
        port map (A=>addsub_cod_1, B=>addsub_as1, Z=>addsub_16b0);

    INV_0: INV
        port map (A=>addsub_as1, Z=>addsub_as1_inv);

    XNOR2_t0: XNOR2
        port map (A=>addsub_cod_2, B=>addsub_as2, Z=>addsub_24b0);

    FF_363: FD1P3DX
        port map (D=>DataA(63), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a63);

    FF_362: FD1P3DX
        port map (D=>DataA(62), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a62);

    FF_361: FD1P3DX
        port map (D=>DataA(61), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a61);

    FF_360: FD1P3DX
        port map (D=>DataA(60), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a60);

    FF_359: FD1P3DX
        port map (D=>DataA(59), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a59);

    FF_358: FD1P3DX
        port map (D=>DataA(58), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a58);

    FF_357: FD1P3DX
        port map (D=>DataA(57), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a57);

    FF_356: FD1P3DX
        port map (D=>DataA(56), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a56);

    FF_355: FD1P3DX
        port map (D=>DataA(55), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a55);

    FF_354: FD1P3DX
        port map (D=>DataA(54), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a54);

    FF_353: FD1P3DX
        port map (D=>DataA(53), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a53);

    FF_352: FD1P3DX
        port map (D=>DataA(52), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a52);

    FF_351: FD1P3DX
        port map (D=>DataA(51), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a51);

    FF_350: FD1P3DX
        port map (D=>DataA(50), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a50);

    FF_349: FD1P3DX
        port map (D=>DataA(49), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a49);

    FF_348: FD1P3DX
        port map (D=>DataA(48), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a48);

    FF_347: FD1P3DX
        port map (D=>DataA(47), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a47);

    FF_346: FD1P3DX
        port map (D=>DataA(46), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a46);

    FF_345: FD1P3DX
        port map (D=>DataA(45), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a45);

    FF_344: FD1P3DX
        port map (D=>DataA(44), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a44);

    FF_343: FD1P3DX
        port map (D=>DataA(43), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a43);

    FF_342: FD1P3DX
        port map (D=>DataA(42), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a42);

    FF_341: FD1P3DX
        port map (D=>DataA(41), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a41);

    FF_340: FD1P3DX
        port map (D=>DataA(40), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a40);

    FF_339: FD1P3DX
        port map (D=>DataA(39), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a39);

    FF_338: FD1P3DX
        port map (D=>DataA(38), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a38);

    FF_337: FD1P3DX
        port map (D=>DataA(37), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a37);

    FF_336: FD1P3DX
        port map (D=>DataA(36), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a36);

    FF_335: FD1P3DX
        port map (D=>DataA(35), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a35);

    FF_334: FD1P3DX
        port map (D=>DataA(34), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a34);

    FF_333: FD1P3DX
        port map (D=>DataA(33), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a33);

    FF_332: FD1P3DX
        port map (D=>DataA(32), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a32);

    FF_331: FD1P3DX
        port map (D=>DataA(31), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a31);

    FF_330: FD1P3DX
        port map (D=>DataA(30), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a30);

    FF_329: FD1P3DX
        port map (D=>DataA(29), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a29);

    FF_328: FD1P3DX
        port map (D=>DataA(28), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a28);

    FF_327: FD1P3DX
        port map (D=>DataA(27), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a27);

    FF_326: FD1P3DX
        port map (D=>DataA(26), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a26);

    FF_325: FD1P3DX
        port map (D=>DataA(25), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a25);

    FF_324: FD1P3DX
        port map (D=>DataA(24), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a24);

    FF_323: FD1P3DX
        port map (D=>DataA(23), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a23);

    FF_322: FD1P3DX
        port map (D=>DataA(22), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a22);

    FF_321: FD1P3DX
        port map (D=>DataA(21), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a21);

    FF_320: FD1P3DX
        port map (D=>DataA(20), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a20);

    FF_319: FD1P3DX
        port map (D=>DataA(19), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a19);

    FF_318: FD1P3DX
        port map (D=>DataA(18), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a18);

    FF_317: FD1P3DX
        port map (D=>DataA(17), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a17);

    FF_316: FD1P3DX
        port map (D=>DataA(16), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a16);

    FF_315: FD1P3DX
        port map (D=>DataA(15), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_a15);

    FF_314: FD1P3DX
        port map (D=>DataB(63), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b63);

    FF_313: FD1P3DX
        port map (D=>DataB(62), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b62);

    FF_312: FD1P3DX
        port map (D=>DataB(61), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b61);

    FF_311: FD1P3DX
        port map (D=>DataB(60), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b60);

    FF_310: FD1P3DX
        port map (D=>DataB(59), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b59);

    FF_309: FD1P3DX
        port map (D=>DataB(58), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b58);

    FF_308: FD1P3DX
        port map (D=>DataB(57), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b57);

    FF_307: FD1P3DX
        port map (D=>DataB(56), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b56);

    FF_306: FD1P3DX
        port map (D=>DataB(55), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b55);

    FF_305: FD1P3DX
        port map (D=>DataB(54), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b54);

    FF_304: FD1P3DX
        port map (D=>DataB(53), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b53);

    FF_303: FD1P3DX
        port map (D=>DataB(52), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b52);

    FF_302: FD1P3DX
        port map (D=>DataB(51), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b51);

    FF_301: FD1P3DX
        port map (D=>DataB(50), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b50);

    FF_300: FD1P3DX
        port map (D=>DataB(49), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b49);

    FF_299: FD1P3DX
        port map (D=>DataB(48), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b48);

    FF_298: FD1P3DX
        port map (D=>DataB(47), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b47);

    FF_297: FD1P3DX
        port map (D=>DataB(46), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b46);

    FF_296: FD1P3DX
        port map (D=>DataB(45), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b45);

    FF_295: FD1P3DX
        port map (D=>DataB(44), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b44);

    FF_294: FD1P3DX
        port map (D=>DataB(43), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b43);

    FF_293: FD1P3DX
        port map (D=>DataB(42), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b42);

    FF_292: FD1P3DX
        port map (D=>DataB(41), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b41);

    FF_291: FD1P3DX
        port map (D=>DataB(40), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b40);

    FF_290: FD1P3DX
        port map (D=>DataB(39), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b39);

    FF_289: FD1P3DX
        port map (D=>DataB(38), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b38);

    FF_288: FD1P3DX
        port map (D=>DataB(37), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b37);

    FF_287: FD1P3DX
        port map (D=>DataB(36), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b36);

    FF_286: FD1P3DX
        port map (D=>DataB(35), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b35);

    FF_285: FD1P3DX
        port map (D=>DataB(34), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b34);

    FF_284: FD1P3DX
        port map (D=>DataB(33), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b33);

    FF_283: FD1P3DX
        port map (D=>DataB(32), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b32);

    FF_282: FD1P3DX
        port map (D=>DataB(31), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b31);

    FF_281: FD1P3DX
        port map (D=>DataB(30), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b30);

    FF_280: FD1P3DX
        port map (D=>DataB(29), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b29);

    FF_279: FD1P3DX
        port map (D=>DataB(28), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b28);

    FF_278: FD1P3DX
        port map (D=>DataB(27), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b27);

    FF_277: FD1P3DX
        port map (D=>DataB(26), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b26);

    FF_276: FD1P3DX
        port map (D=>DataB(25), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b25);

    FF_275: FD1P3DX
        port map (D=>DataB(24), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b24);

    FF_274: FD1P3DX
        port map (D=>DataB(23), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b23);

    FF_273: FD1P3DX
        port map (D=>DataB(22), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b22);

    FF_272: FD1P3DX
        port map (D=>DataB(21), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b21);

    FF_271: FD1P3DX
        port map (D=>DataB(20), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b20);

    FF_270: FD1P3DX
        port map (D=>DataB(19), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b19);

    FF_269: FD1P3DX
        port map (D=>DataB(18), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b18);

    FF_268: FD1P3DX
        port map (D=>DataB(17), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b17);

    FF_267: FD1P3DX
        port map (D=>DataB(16), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b16);

    FF_266: FD1P3DX
        port map (D=>DataB(15), SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_b15);

    FF_265: FD1P3DX
        port map (D=>tsum14, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum14);

    FF_264: FD1P3DX
        port map (D=>tsum13, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum13);

    FF_263: FD1P3DX
        port map (D=>tsum12, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum12);

    FF_262: FD1P3DX
        port map (D=>tsum11, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum11);

    FF_261: FD1P3DX
        port map (D=>tsum10, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum10);

    FF_260: FD1P3DX
        port map (D=>tsum9, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum9);

    FF_259: FD1P3DX
        port map (D=>tsum8, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum8);

    FF_258: FD1P3DX
        port map (D=>tsum7, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum7);

    FF_257: FD1P3DX
        port map (D=>tsum6, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum6);

    FF_256: FD1P3DX
        port map (D=>tsum5, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum5);

    FF_255: FD1P3DX
        port map (D=>tsum4, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum4);

    FF_254: FD1P3DX
        port map (D=>tsum3, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum3);

    FF_253: FD1P3DX
        port map (D=>tsum2, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum2);

    FF_252: FD1P3DX
        port map (D=>tsum1, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum1);

    FF_251: FD1P3DX
        port map (D=>tsum0, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>r0_sum0);

    FF_250: FD1P3DX
        port map (D=>co7d, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>addsub_cod_0);

    FF_249: FD1P3DX
        port map (D=>ClockEn, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>addsub_ce0);

    FF_248: FD1P3DX
        port map (D=>Add_Sub, SP=>ClockEn, CK=>Clock, CD=>Reset, 
            Q=>addsub_as0);

    FF_247: FD1P3DX
        port map (D=>r0_a63, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a63);

    FF_246: FD1P3DX
        port map (D=>r0_a62, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a62);

    FF_245: FD1P3DX
        port map (D=>r0_a61, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a61);

    FF_244: FD1P3DX
        port map (D=>r0_a60, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a60);

    FF_243: FD1P3DX
        port map (D=>r0_a59, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a59);

    FF_242: FD1P3DX
        port map (D=>r0_a58, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a58);

    FF_241: FD1P3DX
        port map (D=>r0_a57, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a57);

    FF_240: FD1P3DX
        port map (D=>r0_a56, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a56);

    FF_239: FD1P3DX
        port map (D=>r0_a55, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a55);

    FF_238: FD1P3DX
        port map (D=>r0_a54, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a54);

    FF_237: FD1P3DX
        port map (D=>r0_a53, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a53);

    FF_236: FD1P3DX
        port map (D=>r0_a52, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a52);

    FF_235: FD1P3DX
        port map (D=>r0_a51, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a51);

    FF_234: FD1P3DX
        port map (D=>r0_a50, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a50);

    FF_233: FD1P3DX
        port map (D=>r0_a49, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a49);

    FF_232: FD1P3DX
        port map (D=>r0_a48, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a48);

    FF_231: FD1P3DX
        port map (D=>r0_a47, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a47);

    FF_230: FD1P3DX
        port map (D=>r0_a46, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a46);

    FF_229: FD1P3DX
        port map (D=>r0_a45, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a45);

    FF_228: FD1P3DX
        port map (D=>r0_a44, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a44);

    FF_227: FD1P3DX
        port map (D=>r0_a43, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a43);

    FF_226: FD1P3DX
        port map (D=>r0_a42, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a42);

    FF_225: FD1P3DX
        port map (D=>r0_a41, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a41);

    FF_224: FD1P3DX
        port map (D=>r0_a40, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a40);

    FF_223: FD1P3DX
        port map (D=>r0_a39, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a39);

    FF_222: FD1P3DX
        port map (D=>r0_a38, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a38);

    FF_221: FD1P3DX
        port map (D=>r0_a37, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a37);

    FF_220: FD1P3DX
        port map (D=>r0_a36, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a36);

    FF_219: FD1P3DX
        port map (D=>r0_a35, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a35);

    FF_218: FD1P3DX
        port map (D=>r0_a34, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a34);

    FF_217: FD1P3DX
        port map (D=>r0_a33, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a33);

    FF_216: FD1P3DX
        port map (D=>r0_a32, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a32);

    FF_215: FD1P3DX
        port map (D=>r0_a31, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_a31);

    FF_214: FD1P3DX
        port map (D=>r0_b63, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b63);

    FF_213: FD1P3DX
        port map (D=>r0_b62, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b62);

    FF_212: FD1P3DX
        port map (D=>r0_b61, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b61);

    FF_211: FD1P3DX
        port map (D=>r0_b60, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b60);

    FF_210: FD1P3DX
        port map (D=>r0_b59, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b59);

    FF_209: FD1P3DX
        port map (D=>r0_b58, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b58);

    FF_208: FD1P3DX
        port map (D=>r0_b57, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b57);

    FF_207: FD1P3DX
        port map (D=>r0_b56, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b56);

    FF_206: FD1P3DX
        port map (D=>r0_b55, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b55);

    FF_205: FD1P3DX
        port map (D=>r0_b54, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b54);

    FF_204: FD1P3DX
        port map (D=>r0_b53, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b53);

    FF_203: FD1P3DX
        port map (D=>r0_b52, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b52);

    FF_202: FD1P3DX
        port map (D=>r0_b51, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b51);

    FF_201: FD1P3DX
        port map (D=>r0_b50, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b50);

    FF_200: FD1P3DX
        port map (D=>r0_b49, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b49);

    FF_199: FD1P3DX
        port map (D=>r0_b48, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b48);

    FF_198: FD1P3DX
        port map (D=>r0_b47, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b47);

    FF_197: FD1P3DX
        port map (D=>r0_b46, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b46);

    FF_196: FD1P3DX
        port map (D=>r0_b45, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b45);

    FF_195: FD1P3DX
        port map (D=>r0_b44, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b44);

    FF_194: FD1P3DX
        port map (D=>r0_b43, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b43);

    FF_193: FD1P3DX
        port map (D=>r0_b42, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b42);

    FF_192: FD1P3DX
        port map (D=>r0_b41, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b41);

    FF_191: FD1P3DX
        port map (D=>r0_b40, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b40);

    FF_190: FD1P3DX
        port map (D=>r0_b39, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b39);

    FF_189: FD1P3DX
        port map (D=>r0_b38, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b38);

    FF_188: FD1P3DX
        port map (D=>r0_b37, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b37);

    FF_187: FD1P3DX
        port map (D=>r0_b36, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b36);

    FF_186: FD1P3DX
        port map (D=>r0_b35, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b35);

    FF_185: FD1P3DX
        port map (D=>r0_b34, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b34);

    FF_184: FD1P3DX
        port map (D=>r0_b33, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b33);

    FF_183: FD1P3DX
        port map (D=>r0_b32, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b32);

    FF_182: FD1P3DX
        port map (D=>r0_b31, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_b31);

    FF_181: FD1P3DX
        port map (D=>tsum30, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum30);

    FF_180: FD1P3DX
        port map (D=>tsum29, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum29);

    FF_179: FD1P3DX
        port map (D=>tsum28, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum28);

    FF_178: FD1P3DX
        port map (D=>tsum27, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum27);

    FF_177: FD1P3DX
        port map (D=>tsum26, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum26);

    FF_176: FD1P3DX
        port map (D=>tsum25, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum25);

    FF_175: FD1P3DX
        port map (D=>tsum24, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum24);

    FF_174: FD1P3DX
        port map (D=>tsum23, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum23);

    FF_173: FD1P3DX
        port map (D=>tsum22, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum22);

    FF_172: FD1P3DX
        port map (D=>tsum21, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum21);

    FF_171: FD1P3DX
        port map (D=>tsum20, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum20);

    FF_170: FD1P3DX
        port map (D=>tsum19, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum19);

    FF_169: FD1P3DX
        port map (D=>tsum18, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum18);

    FF_168: FD1P3DX
        port map (D=>tsum17, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum17);

    FF_167: FD1P3DX
        port map (D=>tsum16, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum16);

    FF_166: FD1P3DX
        port map (D=>tsum15, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum15);

    FF_165: FD1P3DX
        port map (D=>r0_sum14, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum14);

    FF_164: FD1P3DX
        port map (D=>r0_sum13, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum13);

    FF_163: FD1P3DX
        port map (D=>r0_sum12, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum12);

    FF_162: FD1P3DX
        port map (D=>r0_sum11, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum11);

    FF_161: FD1P3DX
        port map (D=>r0_sum10, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum10);

    FF_160: FD1P3DX
        port map (D=>r0_sum9, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum9);

    FF_159: FD1P3DX
        port map (D=>r0_sum8, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum8);

    FF_158: FD1P3DX
        port map (D=>r0_sum7, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum7);

    FF_157: FD1P3DX
        port map (D=>r0_sum6, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum6);

    FF_156: FD1P3DX
        port map (D=>r0_sum5, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum5);

    FF_155: FD1P3DX
        port map (D=>r0_sum4, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum4);

    FF_154: FD1P3DX
        port map (D=>r0_sum3, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum3);

    FF_153: FD1P3DX
        port map (D=>r0_sum2, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum2);

    FF_152: FD1P3DX
        port map (D=>r0_sum1, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum1);

    FF_151: FD1P3DX
        port map (D=>r0_sum0, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>r1_sum0);

    FF_150: FD1P3DX
        port map (D=>co16, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>addsub_cod_1);

    FF_149: FD1P3DX
        port map (D=>addsub_ce0, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>addsub_ce1);

    FF_148: FD1P3DX
        port map (D=>addsub_as0, SP=>addsub_ce0, CK=>Clock, CD=>Reset, 
            Q=>addsub_as1);

    FF_147: FD1P3DX
        port map (D=>r1_a63, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a63);

    FF_146: FD1P3DX
        port map (D=>r1_a62, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a62);

    FF_145: FD1P3DX
        port map (D=>r1_a61, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a61);

    FF_144: FD1P3DX
        port map (D=>r1_a60, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a60);

    FF_143: FD1P3DX
        port map (D=>r1_a59, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a59);

    FF_142: FD1P3DX
        port map (D=>r1_a58, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a58);

    FF_141: FD1P3DX
        port map (D=>r1_a57, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a57);

    FF_140: FD1P3DX
        port map (D=>r1_a56, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a56);

    FF_139: FD1P3DX
        port map (D=>r1_a55, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a55);

    FF_138: FD1P3DX
        port map (D=>r1_a54, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a54);

    FF_137: FD1P3DX
        port map (D=>r1_a53, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a53);

    FF_136: FD1P3DX
        port map (D=>r1_a52, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a52);

    FF_135: FD1P3DX
        port map (D=>r1_a51, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a51);

    FF_134: FD1P3DX
        port map (D=>r1_a50, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a50);

    FF_133: FD1P3DX
        port map (D=>r1_a49, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a49);

    FF_132: FD1P3DX
        port map (D=>r1_a48, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a48);

    FF_131: FD1P3DX
        port map (D=>r1_a47, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_a47);

    FF_130: FD1P3DX
        port map (D=>r1_b63, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b63);

    FF_129: FD1P3DX
        port map (D=>r1_b62, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b62);

    FF_128: FD1P3DX
        port map (D=>r1_b61, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b61);

    FF_127: FD1P3DX
        port map (D=>r1_b60, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b60);

    FF_126: FD1P3DX
        port map (D=>r1_b59, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b59);

    FF_125: FD1P3DX
        port map (D=>r1_b58, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b58);

    FF_124: FD1P3DX
        port map (D=>r1_b57, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b57);

    FF_123: FD1P3DX
        port map (D=>r1_b56, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b56);

    FF_122: FD1P3DX
        port map (D=>r1_b55, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b55);

    FF_121: FD1P3DX
        port map (D=>r1_b54, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b54);

    FF_120: FD1P3DX
        port map (D=>r1_b53, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b53);

    FF_119: FD1P3DX
        port map (D=>r1_b52, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b52);

    FF_118: FD1P3DX
        port map (D=>r1_b51, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b51);

    FF_117: FD1P3DX
        port map (D=>r1_b50, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b50);

    FF_116: FD1P3DX
        port map (D=>r1_b49, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b49);

    FF_115: FD1P3DX
        port map (D=>r1_b48, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b48);

    FF_114: FD1P3DX
        port map (D=>r1_b47, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_b47);

    FF_113: FD1P3DX
        port map (D=>tsum46, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum46);

    FF_112: FD1P3DX
        port map (D=>tsum45, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum45);

    FF_111: FD1P3DX
        port map (D=>tsum44, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum44);

    FF_110: FD1P3DX
        port map (D=>tsum43, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum43);

    FF_109: FD1P3DX
        port map (D=>tsum42, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum42);

    FF_108: FD1P3DX
        port map (D=>tsum41, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum41);

    FF_107: FD1P3DX
        port map (D=>tsum40, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum40);

    FF_106: FD1P3DX
        port map (D=>tsum39, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum39);

    FF_105: FD1P3DX
        port map (D=>tsum38, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum38);

    FF_104: FD1P3DX
        port map (D=>tsum37, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum37);

    FF_103: FD1P3DX
        port map (D=>tsum36, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum36);

    FF_102: FD1P3DX
        port map (D=>tsum35, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum35);

    FF_101: FD1P3DX
        port map (D=>tsum34, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum34);

    FF_100: FD1P3DX
        port map (D=>tsum33, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum33);

    FF_99: FD1P3DX
        port map (D=>tsum32, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum32);

    FF_98: FD1P3DX
        port map (D=>tsum31, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum31);

    FF_97: FD1P3DX
        port map (D=>r1_sum30, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum30);

    FF_96: FD1P3DX
        port map (D=>r1_sum29, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum29);

    FF_95: FD1P3DX
        port map (D=>r1_sum28, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum28);

    FF_94: FD1P3DX
        port map (D=>r1_sum27, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum27);

    FF_93: FD1P3DX
        port map (D=>r1_sum26, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum26);

    FF_92: FD1P3DX
        port map (D=>r1_sum25, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum25);

    FF_91: FD1P3DX
        port map (D=>r1_sum24, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum24);

    FF_90: FD1P3DX
        port map (D=>r1_sum23, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum23);

    FF_89: FD1P3DX
        port map (D=>r1_sum22, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum22);

    FF_88: FD1P3DX
        port map (D=>r1_sum21, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum21);

    FF_87: FD1P3DX
        port map (D=>r1_sum20, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum20);

    FF_86: FD1P3DX
        port map (D=>r1_sum19, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum19);

    FF_85: FD1P3DX
        port map (D=>r1_sum18, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum18);

    FF_84: FD1P3DX
        port map (D=>r1_sum17, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum17);

    FF_83: FD1P3DX
        port map (D=>r1_sum16, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum16);

    FF_82: FD1P3DX
        port map (D=>r1_sum15, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum15);

    FF_81: FD1P3DX
        port map (D=>r1_sum14, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum14);

    FF_80: FD1P3DX
        port map (D=>r1_sum13, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum13);

    FF_79: FD1P3DX
        port map (D=>r1_sum12, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum12);

    FF_78: FD1P3DX
        port map (D=>r1_sum11, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum11);

    FF_77: FD1P3DX
        port map (D=>r1_sum10, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum10);

    FF_76: FD1P3DX
        port map (D=>r1_sum9, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum9);

    FF_75: FD1P3DX
        port map (D=>r1_sum8, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum8);

    FF_74: FD1P3DX
        port map (D=>r1_sum7, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum7);

    FF_73: FD1P3DX
        port map (D=>r1_sum6, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum6);

    FF_72: FD1P3DX
        port map (D=>r1_sum5, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum5);

    FF_71: FD1P3DX
        port map (D=>r1_sum4, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum4);

    FF_70: FD1P3DX
        port map (D=>r1_sum3, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum3);

    FF_69: FD1P3DX
        port map (D=>r1_sum2, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum2);

    FF_68: FD1P3DX
        port map (D=>r1_sum1, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum1);

    FF_67: FD1P3DX
        port map (D=>r1_sum0, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>r2_sum0);

    FF_66: FD1P3DX
        port map (D=>co24, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>addsub_cod_2);

    FF_65: FD1P3DX
        port map (D=>addsub_ce1, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>addsub_ce2);

    FF_64: FD1P3DX
        port map (D=>addsub_as1, SP=>addsub_ce1, CK=>Clock, CD=>Reset, 
            Q=>addsub_as2);

    FF_63: FD1P3DX
        port map (D=>tsum63, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum63);

    FF_62: FD1P3DX
        port map (D=>tsum62, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum62);

    FF_61: FD1P3DX
        port map (D=>tsum61, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum61);

    FF_60: FD1P3DX
        port map (D=>tsum60, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum60);

    FF_59: FD1P3DX
        port map (D=>tsum59, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum59);

    FF_58: FD1P3DX
        port map (D=>tsum58, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum58);

    FF_57: FD1P3DX
        port map (D=>tsum57, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum57);

    FF_56: FD1P3DX
        port map (D=>tsum56, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum56);

    FF_55: FD1P3DX
        port map (D=>tsum55, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum55);

    FF_54: FD1P3DX
        port map (D=>tsum54, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum54);

    FF_53: FD1P3DX
        port map (D=>tsum53, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum53);

    FF_52: FD1P3DX
        port map (D=>tsum52, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum52);

    FF_51: FD1P3DX
        port map (D=>tsum51, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum51);

    FF_50: FD1P3DX
        port map (D=>tsum50, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum50);

    FF_49: FD1P3DX
        port map (D=>tsum49, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum49);

    FF_48: FD1P3DX
        port map (D=>tsum48, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum48);

    FF_47: FD1P3DX
        port map (D=>tsum47, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum47);

    FF_46: FD1P3DX
        port map (D=>r2_sum46, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum46);

    FF_45: FD1P3DX
        port map (D=>r2_sum45, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum45);

    FF_44: FD1P3DX
        port map (D=>r2_sum44, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum44);

    FF_43: FD1P3DX
        port map (D=>r2_sum43, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum43);

    FF_42: FD1P3DX
        port map (D=>r2_sum42, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum42);

    FF_41: FD1P3DX
        port map (D=>r2_sum41, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum41);

    FF_40: FD1P3DX
        port map (D=>r2_sum40, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum40);

    FF_39: FD1P3DX
        port map (D=>r2_sum39, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum39);

    FF_38: FD1P3DX
        port map (D=>r2_sum38, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum38);

    FF_37: FD1P3DX
        port map (D=>r2_sum37, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum37);

    FF_36: FD1P3DX
        port map (D=>r2_sum36, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum36);

    FF_35: FD1P3DX
        port map (D=>r2_sum35, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum35);

    FF_34: FD1P3DX
        port map (D=>r2_sum34, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum34);

    FF_33: FD1P3DX
        port map (D=>r2_sum33, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum33);

    FF_32: FD1P3DX
        port map (D=>r2_sum32, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum32);

    FF_31: FD1P3DX
        port map (D=>r2_sum31, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum31);

    FF_30: FD1P3DX
        port map (D=>r2_sum30, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum30);

    FF_29: FD1P3DX
        port map (D=>r2_sum29, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum29);

    FF_28: FD1P3DX
        port map (D=>r2_sum28, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum28);

    FF_27: FD1P3DX
        port map (D=>r2_sum27, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum27);

    FF_26: FD1P3DX
        port map (D=>r2_sum26, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum26);

    FF_25: FD1P3DX
        port map (D=>r2_sum25, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum25);

    FF_24: FD1P3DX
        port map (D=>r2_sum24, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum24);

    FF_23: FD1P3DX
        port map (D=>r2_sum23, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum23);

    FF_22: FD1P3DX
        port map (D=>r2_sum22, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum22);

    FF_21: FD1P3DX
        port map (D=>r2_sum21, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum21);

    FF_20: FD1P3DX
        port map (D=>r2_sum20, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum20);

    FF_19: FD1P3DX
        port map (D=>r2_sum19, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum19);

    FF_18: FD1P3DX
        port map (D=>r2_sum18, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum18);

    FF_17: FD1P3DX
        port map (D=>r2_sum17, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum17);

    FF_16: FD1P3DX
        port map (D=>r2_sum16, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum16);

    FF_15: FD1P3DX
        port map (D=>r2_sum15, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum15);

    FF_14: FD1P3DX
        port map (D=>r2_sum14, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum14);

    FF_13: FD1P3DX
        port map (D=>r2_sum13, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum13);

    FF_12: FD1P3DX
        port map (D=>r2_sum12, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum12);

    FF_11: FD1P3DX
        port map (D=>r2_sum11, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum11);

    FF_10: FD1P3DX
        port map (D=>r2_sum10, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum10);

    FF_9: FD1P3DX
        port map (D=>r2_sum9, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum9);

    FF_8: FD1P3DX
        port map (D=>r2_sum8, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum8);

    FF_7: FD1P3DX
        port map (D=>r2_sum7, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum7);

    FF_6: FD1P3DX
        port map (D=>r2_sum6, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum6);

    FF_5: FD1P3DX
        port map (D=>r2_sum5, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum5);

    FF_4: FD1P3DX
        port map (D=>r2_sum4, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum4);

    FF_3: FD1P3DX
        port map (D=>r2_sum3, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum3);

    FF_2: FD1P3DX
        port map (D=>r2_sum2, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum2);

    FF_1: FD1P3DX
        port map (D=>r2_sum1, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum1);

    FF_0: FD1P3DX
        port map (D=>r2_sum0, SP=>addsub_ce2, CK=>Clock, CD=>Reset, 
            Q=>r3_sum0);

    precin_inst199: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"0000", 
        INIT0=> X"0000")
        port map (A0=>scuba_vhi, A1=>scuba_vhi, B0=>scuba_vhi, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, COUT=>precin);

    addsub_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>add_sub_inv, A1=>DataA(0), B0=>scuba_vlo, 
            B1=>DataB(0), C0=>Add_Sub, C1=>Add_Sub, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>precin, S0=>open, S1=>tsum0, COUT=>co0);

    addsub_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>DataA(1), A1=>DataA(2), B0=>DataB(1), B1=>DataB(2), 
            C0=>Add_Sub, C1=>Add_Sub, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co0, S0=>tsum1, S1=>tsum2, COUT=>co1);

    addsub_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>DataA(3), A1=>DataA(4), B0=>DataB(3), B1=>DataB(4), 
            C0=>Add_Sub, C1=>Add_Sub, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co1, S0=>tsum3, S1=>tsum4, COUT=>co2);

    addsub_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>DataA(5), A1=>DataA(6), B0=>DataB(5), B1=>DataB(6), 
            C0=>Add_Sub, C1=>Add_Sub, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co2, S0=>tsum5, S1=>tsum6, COUT=>co3);

    addsub_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>DataA(7), A1=>DataA(8), B0=>DataB(7), B1=>DataB(8), 
            C0=>Add_Sub, C1=>Add_Sub, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co3, S0=>tsum7, S1=>tsum8, COUT=>co4);

    addsub_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>DataA(9), A1=>DataA(10), B0=>DataB(9), 
            B1=>DataB(10), C0=>Add_Sub, C1=>Add_Sub, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co4, S0=>tsum9, S1=>tsum10, COUT=>co5);

    addsub_6: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>DataA(11), A1=>DataA(12), B0=>DataB(11), 
            B1=>DataB(12), C0=>Add_Sub, C1=>Add_Sub, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co5, S0=>tsum11, S1=>tsum12, COUT=>co6);

    addsub_7: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>DataA(13), A1=>DataA(14), B0=>DataB(13), 
            B1=>DataB(14), C0=>Add_Sub, C1=>Add_Sub, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co6, S0=>tsum13, S1=>tsum14, COUT=>co7);

    addsubd: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co7, S0=>co7d, S1=>open, COUT=>open);

    addsub_8: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>addsub_cod_0, A1=>r0_a15, B0=>addsub_8b0, 
            B1=>r0_b15, C0=>addsub_as0, C1=>addsub_as0, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>groupcin, S0=>open, S1=>tsum15, 
            COUT=>co8);

    groupcin_inst487: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"0000", 
        INIT0=> X"0000")
        port map (A0=>scuba_vhi, A1=>scuba_vhi, B0=>scuba_vhi, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, COUT=>groupcin);

    addsub_9: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r0_a16, A1=>r0_a17, B0=>r0_b16, B1=>r0_b17, 
            C0=>addsub_as0, C1=>addsub_as0, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co8, S0=>tsum16, S1=>tsum17, COUT=>co9);

    addsub_10: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r0_a18, A1=>r0_a19, B0=>r0_b18, B1=>r0_b19, 
            C0=>addsub_as0, C1=>addsub_as0, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co9, S0=>tsum18, S1=>tsum19, COUT=>co10);

    addsub_11: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r0_a20, A1=>r0_a21, B0=>r0_b20, B1=>r0_b21, 
            C0=>addsub_as0, C1=>addsub_as0, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co10, S0=>tsum20, S1=>tsum21, COUT=>co11);

    addsub_12: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r0_a22, A1=>r0_a23, B0=>r0_b22, B1=>r0_b23, 
            C0=>addsub_as0, C1=>addsub_as0, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co11, S0=>tsum22, S1=>tsum23, COUT=>co12);

    addsub_13: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r0_a24, A1=>r0_a25, B0=>r0_b24, B1=>r0_b25, 
            C0=>addsub_as0, C1=>addsub_as0, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co12, S0=>tsum24, S1=>tsum25, COUT=>co13);

    addsub_14: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r0_a26, A1=>r0_a27, B0=>r0_b26, B1=>r0_b27, 
            C0=>addsub_as0, C1=>addsub_as0, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co13, S0=>tsum26, S1=>tsum27, COUT=>co14);

    addsub_15: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r0_a28, A1=>r0_a29, B0=>r0_b28, B1=>r0_b29, 
            C0=>addsub_as0, C1=>addsub_as0, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co14, S0=>tsum28, S1=>tsum29, COUT=>co15);

    addsub_16_d: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r0_a30, A1=>addsub_as0_inv, B0=>r0_b30, 
            B1=>scuba_vlo, C0=>addsub_as0, C1=>addsub_as0, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co15, S0=>tsum30, S1=>co16, COUT=>open);

    addsub_16: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>addsub_cod_1, A1=>r1_a31, B0=>addsub_16b0, 
            B1=>r1_b31, C0=>addsub_as1, C1=>addsub_as1, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>groupcin_1, S0=>open, S1=>tsum31, 
            COUT=>co16_1);

    groupcin_inst583: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"0000", 
        INIT0=> X"0000")
        port map (A0=>scuba_vhi, A1=>scuba_vhi, B0=>scuba_vhi, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, 
            COUT=>groupcin_1);

    addsub_17: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r1_a32, A1=>r1_a33, B0=>r1_b32, B1=>r1_b33, 
            C0=>addsub_as1, C1=>addsub_as1, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co16_1, S0=>tsum32, S1=>tsum33, COUT=>co17);

    addsub_18: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r1_a34, A1=>r1_a35, B0=>r1_b34, B1=>r1_b35, 
            C0=>addsub_as1, C1=>addsub_as1, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co17, S0=>tsum34, S1=>tsum35, COUT=>co18);

    addsub_19: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r1_a36, A1=>r1_a37, B0=>r1_b36, B1=>r1_b37, 
            C0=>addsub_as1, C1=>addsub_as1, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co18, S0=>tsum36, S1=>tsum37, COUT=>co19);

    addsub_20: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r1_a38, A1=>r1_a39, B0=>r1_b38, B1=>r1_b39, 
            C0=>addsub_as1, C1=>addsub_as1, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co19, S0=>tsum38, S1=>tsum39, COUT=>co20);

    addsub_21: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r1_a40, A1=>r1_a41, B0=>r1_b40, B1=>r1_b41, 
            C0=>addsub_as1, C1=>addsub_as1, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co20, S0=>tsum40, S1=>tsum41, COUT=>co21);

    addsub_22: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r1_a42, A1=>r1_a43, B0=>r1_b42, B1=>r1_b43, 
            C0=>addsub_as1, C1=>addsub_as1, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co21, S0=>tsum42, S1=>tsum43, COUT=>co22);

    addsub_23: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r1_a44, A1=>r1_a45, B0=>r1_b44, B1=>r1_b45, 
            C0=>addsub_as1, C1=>addsub_as1, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co22, S0=>tsum44, S1=>tsum45, COUT=>co23);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    addsub_24_d: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r1_a46, A1=>addsub_as1_inv, B0=>r1_b46, 
            B1=>scuba_vlo, C0=>addsub_as1, C1=>addsub_as1, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co23, S0=>tsum46, S1=>co24, COUT=>open);

    addsub_24: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>addsub_cod_2, A1=>r2_a47, B0=>addsub_24b0, 
            B1=>r2_b47, C0=>addsub_as2, C1=>addsub_as2, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>groupcin_2, S0=>open, S1=>tsum47, 
            COUT=>co24_1);

    groupcin_inst662: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"0000", 
        INIT0=> X"0000")
        port map (A0=>scuba_vhi, A1=>scuba_vhi, B0=>scuba_vhi, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, 
            COUT=>groupcin_2);

    addsub_25: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r2_a48, A1=>r2_a49, B0=>r2_b48, B1=>r2_b49, 
            C0=>addsub_as2, C1=>addsub_as2, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co24_1, S0=>tsum48, S1=>tsum49, COUT=>co25);

    addsub_26: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r2_a50, A1=>r2_a51, B0=>r2_b50, B1=>r2_b51, 
            C0=>addsub_as2, C1=>addsub_as2, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co25, S0=>tsum50, S1=>tsum51, COUT=>co26);

    addsub_27: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r2_a52, A1=>r2_a53, B0=>r2_b52, B1=>r2_b53, 
            C0=>addsub_as2, C1=>addsub_as2, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co26, S0=>tsum52, S1=>tsum53, COUT=>co27);

    addsub_28: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r2_a54, A1=>r2_a55, B0=>r2_b54, B1=>r2_b55, 
            C0=>addsub_as2, C1=>addsub_as2, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co27, S0=>tsum54, S1=>tsum55, COUT=>co28);

    addsub_29: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r2_a56, A1=>r2_a57, B0=>r2_b56, B1=>r2_b57, 
            C0=>addsub_as2, C1=>addsub_as2, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co28, S0=>tsum56, S1=>tsum57, COUT=>co29);

    addsub_30: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r2_a58, A1=>r2_a59, B0=>r2_b58, B1=>r2_b59, 
            C0=>addsub_as2, C1=>addsub_as2, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co29, S0=>tsum58, S1=>tsum59, COUT=>co30);

    addsub_31: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r2_a60, A1=>r2_a61, B0=>r2_b60, B1=>r2_b61, 
            C0=>addsub_as2, C1=>addsub_as2, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co30, S0=>tsum60, S1=>tsum61, COUT=>co31);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    addsub_32: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"69AA", 
        INIT0=> X"69AA")
        port map (A0=>r2_a62, A1=>r2_a63, B0=>r2_b62, B1=>r2_b63, 
            C0=>addsub_as2, C1=>addsub_as2, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co31, S0=>tsum62, S1=>tsum63, COUT=>open);

    Result(63) <= r3_sum63;
    Result(62) <= r3_sum62;
    Result(61) <= r3_sum61;
    Result(60) <= r3_sum60;
    Result(59) <= r3_sum59;
    Result(58) <= r3_sum58;
    Result(57) <= r3_sum57;
    Result(56) <= r3_sum56;
    Result(55) <= r3_sum55;
    Result(54) <= r3_sum54;
    Result(53) <= r3_sum53;
    Result(52) <= r3_sum52;
    Result(51) <= r3_sum51;
    Result(50) <= r3_sum50;
    Result(49) <= r3_sum49;
    Result(48) <= r3_sum48;
    Result(47) <= r3_sum47;
    Result(46) <= r3_sum46;
    Result(45) <= r3_sum45;
    Result(44) <= r3_sum44;
    Result(43) <= r3_sum43;
    Result(42) <= r3_sum42;
    Result(41) <= r3_sum41;
    Result(40) <= r3_sum40;
    Result(39) <= r3_sum39;
    Result(38) <= r3_sum38;
    Result(37) <= r3_sum37;
    Result(36) <= r3_sum36;
    Result(35) <= r3_sum35;
    Result(34) <= r3_sum34;
    Result(33) <= r3_sum33;
    Result(32) <= r3_sum32;
    Result(31) <= r3_sum31;
    Result(30) <= r3_sum30;
    Result(29) <= r3_sum29;
    Result(28) <= r3_sum28;
    Result(27) <= r3_sum27;
    Result(26) <= r3_sum26;
    Result(25) <= r3_sum25;
    Result(24) <= r3_sum24;
    Result(23) <= r3_sum23;
    Result(22) <= r3_sum22;
    Result(21) <= r3_sum21;
    Result(20) <= r3_sum20;
    Result(19) <= r3_sum19;
    Result(18) <= r3_sum18;
    Result(17) <= r3_sum17;
    Result(16) <= r3_sum16;
    Result(15) <= r3_sum15;
    Result(14) <= r3_sum14;
    Result(13) <= r3_sum13;
    Result(12) <= r3_sum12;
    Result(11) <= r3_sum11;
    Result(10) <= r3_sum10;
    Result(9) <= r3_sum9;
    Result(8) <= r3_sum8;
    Result(7) <= r3_sum7;
    Result(6) <= r3_sum6;
    Result(5) <= r3_sum5;
    Result(4) <= r3_sum4;
    Result(3) <= r3_sum3;
    Result(2) <= r3_sum2;
    Result(1) <= r3_sum1;
    Result(0) <= r3_sum0;
end Structure;
