-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2  Patch Version(s) 132427
-- Module  Version: 3.5
-- Mon Jul 20 17:06:40 2026

-- parameterized module component declaration
component addsub
    port (DataA: in  std_logic_vector(63 downto 0); 
        DataB: in  std_logic_vector(63 downto 0); Add_Sub: in  std_logic; 
        Clock: in  std_logic; Reset: in  std_logic; 
        ClockEn: in  std_logic; 
        Result: out  std_logic_vector(63 downto 0));
end component;

-- parameterized module component instance
__ : addsub
    port map (DataA(63 downto 0)=>__, DataB(63 downto 0)=>__, Add_Sub=>__, 
        Clock=>__, Reset=>__, ClockEn=>__, Result(63 downto 0)=>__);
