-- VHDL testbench template generated by SCUBA Diamond (64-bit) 3.14.0.75.2  Patch Version(s) 132427
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.std_logic_unsigned.all;

use IEEE.math_real.all;

use IEEE.numeric_std.all;

entity tb is
end entity tb;


architecture test of tb is 

    component addsub
        port (DataA : in std_logic_vector(63 downto 0); 
        DataB : in std_logic_vector(63 downto 0); Add_Sub: in std_logic; 
        Clock: in std_logic; Reset: in std_logic; ClockEn: in std_logic; 
        Result : out std_logic_vector(63 downto 0)
    );
    end component;

    signal DataA : std_logic_vector(63 downto 0) := (others => '0');
    signal DataB : std_logic_vector(63 downto 0) := (others => '0');
    signal Add_Sub: std_logic := '0';
    signal Clock: std_logic := '0';
    signal Reset: std_logic := '0';
    signal ClockEn: std_logic := '0';
    signal Result : std_logic_vector(63 downto 0);
begin
    u1 : addsub
        port map (DataA => DataA, DataB => DataB, Add_Sub => Add_Sub, 
            Clock => Clock, Reset => Reset, ClockEn => ClockEn, Result => Result
        );

    process

    begin
      DataA <= (others => '0') ;
      for i in 0 to 200 loop
        wait until Clock'event and Clock = '1';
        DataA <= DataA + '1' after 1 ns;
      end loop;
      wait;
    end process;

    process

    begin
      DataB <= (others => '0') ;
      for i in 0 to 200 loop
        wait until Clock'event and Clock = '1';
        DataB <= DataB + '1' after 1 ns;
      end loop;
      wait;
    end process;

    process

    begin
      Add_Sub <= '1' ;
      for i in 0 to 100 loop
        wait until Clock'event and Clock = '1';
      end loop;
      Add_Sub <= '0' ;
      wait;
    end process;

    Clock <= not Clock after 5.00 ns;

    process

    begin
      Reset <= '1' ;
      wait for 100 ns;
      Reset <= '0' ;
      wait;
    end process;

    process

    begin
      ClockEn <= '1' ;
      wait;
    end process;

end architecture test;
