-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2  Patch Version(s) 132427
-- Module  Version: 6.5
-- Tue Sep 01 06:38:06 2026

-- parameterized module component declaration
component adc_scaler_gain_ram
    port (WrAddress: in  std_logic_vector(8 downto 0); 
        RdAddress: in  std_logic_vector(8 downto 0); 
        Data: in  std_logic_vector(31 downto 0); WE: in  std_logic; 
        RdClock: in  std_logic; RdClockEn: in  std_logic; 
        Reset: in  std_logic; WrClock: in  std_logic; 
        WrClockEn: in  std_logic; Q: out  std_logic_vector(31 downto 0));
end component;

-- parameterized module component instance
__ : adc_scaler_gain_ram
    port map (WrAddress(8 downto 0)=>__, RdAddress(8 downto 0)=>__, Data(31 downto 0)=>__, 
        WE=>__, RdClock=>__, RdClockEn=>__, Reset=>__, WrClock=>__, 
        WrClockEn=>__, Q(31 downto 0)=>__);
