#!/usr/bin/env python3
"""Generate the memory-initialisation files for the adc_scaler gain / offset
EBR IP cores.

  ip/adc_scaler_gain_ram_init.mem    512 x 32, every word = identity gain
                                     = 2**radix  (radix 20 -> 0x00100000)
  ip/adc_scaler_offset_ram_init.mem  512 x 32, every word = 0

Only channels 0..15 are used, but the RAM is 512 deep so every word is
filled -- a stray address then still reads identity / zero, not garbage.

Format: Diamond .mem "AddrHex" (see Diamond help "Memory Initialization
File Format"). Header first (no comments allowed before it), then
`<hexaddr>: <hexdata>` lines. Run with --plain for the "Hex" format
(one hex value per line) instead.
"""

import argparse
from pathlib import Path

DEPTH = 512
WIDTH = 32
RADIX = 20                       # source/top.vhd : constant adc_scaler_radix
IDENTITY_GAIN = 1 << RADIX       # 0x00100000
HEX_DIGITS   = WIDTH // 4                       # 8
ADDR_DIGITS  = ((DEPTH - 1).bit_length() + 3) // 4   # 3  (0..0x1FF)

HERE = Path(__file__).resolve().parent


def write_mem(path: Path, value: int, addressed: bool) -> None:
    fmt = "AddrHex" if addressed else "Hex"
    lines = [
        f"#Format={fmt}",
        f"#Depth={DEPTH}",
        f"#Width={WIDTH}",
        f"#AddrRadix=3",          # 0=Bin 1=Oct 2=Dec 3=Hex (display only)
        f"#DataRadix=3",
        f"#Data",
        f"// {path.name} : {DEPTH} x {WIDTH}, every word 0x{value:0{HEX_DIGITS}X}",
        f"// generated by ip/{Path(__file__).name}",
    ]
    if addressed:
        lines += [f"{a:0{ADDR_DIGITS}X}: {value:0{HEX_DIGITS}X}" for a in range(DEPTH)]
    else:
        lines += [f"{value:0{HEX_DIGITS}X}" for _ in range(DEPTH)]

    path.write_text("\n".join(lines) + "\n")
    print(f"wrote {path}  ({DEPTH} words, {fmt})")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--plain", action="store_true",
                    help="Diamond 'Hex' format (one hex value per line) "
                         "instead of 'AddrHex'")
    args = ap.parse_args()

    write_mem(HERE / "adc_scaler_gain_ram_init.mem", IDENTITY_GAIN, not args.plain)
    write_mem(HERE / "adc_scaler_offset_ram_init.mem", 0, not args.plain)


if __name__ == "__main__":
    main()
